name = "RegistryBrowser"
uuid = "64299e68-9b01-4b5a-be04-faf1e4464d2a"
authors = ["GHTaarn <62629455+GHTaarn@users.noreply.github.com>"]
version = "0.1.0-DEV"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[compat]
InteractiveUtils = "1.7"
Pkg = "1.7 - 1.11"
REPL = "1.7"
julia = "1.7"
